apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.apiGateway.replicas }}
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: {{ .Values.apiGateway.image }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.apiGateway.port }}
          name: http
        args:
        - -addr=:{{ .Values.apiGateway.port }}
        - -influx_url={{ if .Values.influxdb2.enabled }}http://influxdb2.{{ .Release.Namespace }}.svc.cluster.local{{ else }}{{ .Values.apiGateway.influx.url }}{{ end }}
        - -influx_org={{ default .Values.influxdb2.admin.org .Values.apiGateway.influx.org }}
        - -influx_bucket={{ default .Values.influxdb2.admin.bucket .Values.apiGateway.influx.bucket }}
        - -influx_token={{ default .Values.influxdb2.admin.token .Values.apiGateway.influx.token }}
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: api-gateway
  ports:
  - name: http
    port: {{ .Values.apiGateway.port }}
    targetPort: http
