apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.broker.replicas }}
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
      annotations:
        {{- if .Values.prometheusScrape }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.broker.metricsPort }}"
        prometheus.io/path: "/metrics"
        {{- end }}
    spec:
      containers:
      - name: broker
        image: {{ .Values.broker.image }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.broker.grpcPort }}
          name: grpc
        - containerPort: {{ .Values.broker.metricsPort }}
          name: metrics
        args:
        - -grpc_addr=:{{ .Values.broker.grpcPort }}
        - -metrics_addr=:{{ .Values.broker.metricsPort }}
        - -queue_cap=10000
        - -sub_buf=256
---
apiVersion: v1
kind: Service
metadata:
  name: broker
  namespace: {{ .Values.namespace }}
  labels:
    app: broker
spec:
  clusterIP: None
  selector:
    app: broker
  ports:
  - name: grpc
    port: {{ .Values.broker.grpcPort }}
    targetPort: grpc
  - name: metrics
    port: {{ .Values.broker.metricsPort }}
    targetPort: metrics
